name: mimotion

on:
  schedule:
    - cron: "45 10 * * *"
  watch:
    types: [started]

jobs:
  update:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
        
      - name: mimotion
        env:
         PARAMETER: ${{ secrets.PARAMETER }}
        run: |
          bash mimotion.sh $PARAMETER

      - name: delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 0
